### PR TITLE
Attempt to add `JNI_CreateJavaVM()`

### PR DESCRIPTION
**Pull request by kud1ing**

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks!

**Comment by kud1ing** [comment]
Do you plan a new release in the nextish time?

This small addition on its own would probably not justify a release. Except for it would let me get rid of my own function declaration - which also would not be much except for being nice to have.

**Comment by sfackler** [comment]
Done!

**Comment by kud1ing** [comment]
Thanks.

**Pull request merged**
